INSERT INTO ATM (NAME, LOCATION, NOTE20, NOTE50) VALUES ('London1', 'Oxford St', 100, 200);
INSERT INTO ATM (NAME, LOCATION, NOTE20, NOTE50) VALUES ('London2', 'Liverpool St', 10, 5);
INSERT INTO ATM (NAME, LOCATION, NOTE20, NOTE50) VALUES ('London1', 'St Pauls', 5, 10);